# 数组的创建和访问

In [1]:
import numpy as np

In [2]:
list_1 = [1, 2, 3, 4]  # 创建列表
list_1

[1, 2, 3, 4]

In [3]:
array_1 = np.array(list_1) # 生成数组
array_1

array([1, 2, 3, 4])

In [4]:
list_2 = [5,6,7,8]
array_2 = np.array([list_1,list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
array_2.shape # 查看数据的形状

(2, 4)

In [6]:
array_2.size # 查看数据量

8

In [7]:
array_2.dtype # 查看数据类型

dtype('int32')

In [8]:
array_3 = np.array([[1.0,2,3],[4.0,5,6]])
array_3.dtype

dtype('float64')

In [9]:
array_4 = np.arange(1,10,2) # 从1~10生成间距为2的数组
array_4

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(5) # 生成一行五列的0数组

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros([2,3]) # 生成两行三列0数组

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.eye(5)# 生成矩阵

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(5).dtype

dtype('float64')

In [14]:
a = np.arange(1,10) # 生成间距为1的数组
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a[1] # 索引第二位数值

2

In [16]:
a[1:5] # 索引第二位到第五位（左闭右开）

array([2, 3, 4, 5])

In [17]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b[1][0]

4

In [19]:
b[1,0]

4

In [20]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
c[:2,1:]

array([[2, 3],
       [5, 6]])

# 使用pickle序列化numpy array

In [22]:
import pickle
import numpy as np

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
f = open('x.pkl', 'wb')

In [25]:
pickle.dump(x, f)

In [26]:
!ls

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [27]:
f = open('x.pkl', 'rb')

In [28]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.save('one_array', x)

In [30]:
!ls

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [31]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
y = np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
np.savez('two_array.npz', a=x, b=y)

In [34]:
!ls

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [35]:
c = np.load('two_array.npz')

In [36]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# 数组与矩阵运算

### 快速创建数组

In [38]:
np.random.randn(10)

array([ 0.75896502, -0.7286949 , -0.85231547, -0.90034919,  0.71714713,
        0.63959567,  0.20590054, -0.43012393,  1.14171795,  0.57685522])

In [39]:
np.random.randint(10, size=20).reshape(4, 5)

array([[7, 1, 0, 5, 7],
       [3, 6, 6, 4, 8],
       [3, 0, 5, 2, 4],
       [1, 2, 9, 6, 6]])

### 数组运算

In [40]:
a = np.random.randint(10, size=20).reshape(4, 5)
a

array([[8, 3, 2, 1, 1],
       [5, 5, 1, 9, 6],
       [9, 5, 5, 7, 7],
       [9, 9, 8, 6, 6]])

In [41]:
b = np.random.randint(10, size=20).reshape(4, 5)
b

array([[7, 5, 3, 4, 3],
       [5, 4, 2, 1, 3],
       [8, 6, 8, 2, 1],
       [5, 2, 0, 8, 1]])

In [42]:
a + b

array([[15,  8,  5,  5,  4],
       [10,  9,  3, 10,  9],
       [17, 11, 13,  9,  8],
       [14, 11,  8, 14,  7]])

In [43]:
a - b

array([[ 1, -2, -1, -3, -2],
       [ 0,  1, -1,  8,  3],
       [ 1, -1, -3,  5,  6],
       [ 4,  7,  8, -2,  5]])

In [44]:
a * b

array([[56, 15,  6,  4,  3],
       [25, 20,  2,  9, 18],
       [72, 30, 40, 14,  7],
       [45, 18,  0, 48,  6]])

In [45]:
a / b

D:\Program Files (x86)\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[1.14285714, 0.6       , 0.66666667, 0.25      , 0.33333333],
       [1.        , 1.25      , 0.5       , 9.        , 2.        ],
       [1.125     , 0.83333333, 0.625     , 3.5       , 7.        ],
       [1.8       , 4.5       ,        inf, 0.75      , 6.        ]])

In [46]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [47]:
a

array([[8, 3, 2, 1, 1],
       [5, 5, 1, 9, 6],
       [9, 5, 5, 7, 7],
       [9, 9, 8, 6, 6]])

In [48]:
np.mat(a)

matrix([[8, 3, 2, 1, 1],
        [5, 5, 1, 9, 6],
        [9, 5, 5, 7, 7],
        [9, 9, 8, 6, 6]])

### 矩阵的运算

In [49]:
A = np.mat(a)
A

matrix([[8, 3, 2, 1, 1],
        [5, 5, 1, 9, 6],
        [9, 5, 5, 7, 7],
        [9, 9, 8, 6, 6]])

In [50]:
B = np.mat(b)
B

matrix([[7, 5, 3, 4, 3],
        [5, 4, 2, 1, 3],
        [8, 6, 8, 2, 1],
        [5, 2, 0, 8, 1]])

In [51]:
A + B

matrix([[15,  8,  5,  5,  4],
        [10,  9,  3, 10,  9],
        [17, 11, 13,  9,  8],
        [14, 11,  8, 14,  7]])

In [52]:
A - B

matrix([[ 1, -2, -1, -3, -2],
        [ 0,  1, -1,  8,  3],
        [ 1, -1, -3,  5,  6],
        [ 4,  7,  8, -2,  5]])

In [53]:
# A * B

In [54]:
a = np.mat(np.random.randint(10, size=20).reshape(4, 5))
a

matrix([[5, 4, 8, 0, 3],
        [7, 5, 6, 4, 8],
        [6, 1, 5, 4, 7],
        [1, 2, 7, 0, 6]])

In [55]:
b = np.mat(np.random.randint(10, size=20).reshape(5, 4))
b

matrix([[0, 4, 6, 1],
        [1, 4, 3, 6],
        [3, 2, 2, 0],
        [2, 2, 9, 4],
        [7, 0, 7, 0]])

In [56]:
a * b

matrix([[ 49,  52,  79,  29],
        [ 87,  68, 161,  53],
        [ 73,  46, 134,  28],
        [ 65,  26,  68,  13]])

### Array常用函数

In [57]:
a = np.random.randint(10, size=20).reshape(4, 5)
a

array([[3, 2, 9, 6, 3],
       [9, 8, 0, 9, 3],
       [0, 4, 1, 2, 8],
       [1, 8, 6, 1, 8]])

In [58]:
np.unique(a)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [59]:
sum(a)

array([13, 22, 16, 18, 22])

In [60]:
sum(a[:,0])

13

In [61]:
a.max()

9

In [62]:
max(a[0])

9

In [63]:
max(a[:,0])

9